[tool.poetry]
name = "csw"
version = "1.2"
description = "Catalogue service for spatial records over HTTP in the Department of Biodiversity, Conservation and Attractions."
authors = ["ASU <asu@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
psycopg2-binary = "2.8.6"
Django = "2.2.17"
django-extensions = "2.1.9"
django-dotenv = "1.4.2"
dbca-utils = {git = "https://github.com/dbca-wa/dbca-utils.git", rev = "1.0.1"}
dj-database-url = "0.5.0"
gunicorn = "20.0.4"
dj-static = "0.0.6"
django-reversion = "3.0.4"
six = "1.12.0"
lxml = "4.6.3"
pycsw = "2.4.2"
pyproj = "3.0.0.post1"
sqlalchemy = "1.3.19"
djangorestframework = "3.10.1"
django-filter = "2.2.0"
mixer = "6.1.3"

[tool.poetry.dev-dependencies]
ipython = "^7.17.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
